

public class clsCurrencyCodes
{
    
    public class clsCurrencyCodes {
        
        public static let countriesAr: [String] = [
               "الإمارات العربية المتحدة", "الأرجنتين", "أستراليا", "بلغاريا", "البرازيل", "جزر البهاما", "كندا", "سويسرا", "تشيلي", "الصين",
               "كولومبيا", "جمهورية التشيك", "الدنمارك", "جمهورية الدومينيكان", "مصر", "منطقة اليورو", "فيجي", "المملكة المتحدة", "غواتيمالا",
               "هونغ كونغ", "كرواتيا", "المجر", "إندونيسيا", "إسرائيل", "الهند", "آيسلندا", "اليابان", "كوريا الجنوبية", "كازاخستان", "المكسيك",
               "ماليزيا", "النرويج", "نيوزيلندا", "بنما", "بيرو", "الفلبين", "باكستان", "بولندا", "باراغواي", "رومانيا", "روسيا", "المملكة العربية السعودية",
               "السويد", "سنغافورة", "تايلاند", "تركيا", "تايوان", "أوكرانيا", "الولايات المتحدة", "أوروغواي", "جنوب أفريقيا"
           ]

        public static let countriesDe: [String] = [
            "Vereinigte Arabische Emirate", "Argentinien", "Australien", "Bulgarien", "Brasilien", "Bahamas", "Kanada", "Schweiz", "Chile",
            "China", "Kolumbien", "Tschechische Republik", "Dänemark", "Dominikanische Republik", "Ägypten", "Eurozone", "Fidschi",
            "Vereinigtes Königreich", "Guatemala", "Hongkong", "Kroatien", "Ungarn", "Indonesien", "Israel", "Indien", "Island",
            "Japan", "Südkorea", "Kasachstan", "Mexiko", "Malaysia", "Norwegen", "Neuseeland", "Panama", "Peru", "Philippinen",
            "Pakistan", "Polen", "Paraguay", "Rumänien", "Russland", "Saudi-Arabien", "Schweden", "Singapur", "Thailand", "Türkei",
            "Taiwan", "Ukraine", "Vereinigte Staaten", "Uruguay", "Südafrika"
        ]
        
        public static let countriesEs: [String] = [
            "Emiratos Árabes Unidos", "Argentina", "Australia", "Bulgaria", "Brasil", "Bahamas", "Canadá", "Suiza", "Chile", "China",
            "Colombia", "República Checa", "Dinamarca", "República Dominicana", "Egipto", "Zona Euro", "Fiyi", "Reino Unido",
            "Guatemala", "Hong Kong", "Croacia", "Hungría", "Indonesia", "Israel", "India", "Islandia", "Japón", "Corea del Sur",
            "Kazajistán", "México", "Malasia", "Noruega", "Nueva Zelanda", "Panamá", "Perú", "Filipinas", "Pakistán", "Polonia",
            "Paraguay", "Rumanía", "Rusia", "Arabia Saudita", "Suecia", "Singapur", "Tailandia", "Turquía", "Taiwán", "Ucrania",
            "Estados Unidos", "Uruguay", "Sudáfrica"
        ]

        public static let countriesFr: [String] = [
            "Émirats Arabes Unis", "Argentine", "Australie", "Bulgarie", "Brésil", "Bahamas", "Canada", "Suisse", "Chili", "Chine",
            "Colombie", "République tchèque", "Danemark", "République dominicaine", "Égypte", "Zone euro", "Fidji", "Royaume-Uni",
            "Guatemala", "Hong Kong", "Croatie", "Hongrie", "Indonésie", "Israël", "Inde", "Islande", "Japon", "Corée du Sud",
            "Kazakhstan", "Mexique", "Malaisie", "Norvège", "Nouvelle-Zélande", "Panama", "Pérou", "Philippines", "Pakistan",
            "Pologne", "Paraguay", "Roumanie", "Russie", "Arabie Saoudite", "Suède", "Singapour", "Thaïlande", "Turquie", "Taïwan",
            "Ukraine", "États-Unis", "Uruguay", "Afrique du Sud"
        ]
        
        public static let countriesHi: [String] = [
            "संयुक्त अरब अमीरात", "अर्जेंटीना", "ऑस्ट्रेलिया", "बुल्गारिया", "ब्राजील", "बहामा", "कनाडा", "स्विट्ज़रलैंड", "चिली",
            "चीन", "कोलंबिया", "चेक गणराज्य", "डेनमार्क", "डोमिनिकन गणराज्य", "मिस्र", "यूरो ज़ोन", "फिजी", "यूनाइटेड किंगडम",
            "ग्वाटेमाला", "हॉंग कोंग", "क्रोएशिया", "हंगरी", "इंडोनेशिया", "इज़राइल", "भारत", "आइसलैंड", "जापान", "दक्षिण कोरिया",
            "कजाखस्तान", "मेक्सिको", "मलेशिया", "नॉर्वे", "न्यूज़ीलैंड", "पनामा", "पेरू", "फिलीपींस", "पाकिस्तान", "पोलैंड",
            "पराग्वे", "रोमानिया", "रूस", "सऊदी अरब", "स्वीडन", "सिंगापुर", "थाईलैंड", "तुर्की", "ताइवान", "यूक्रेन", "संयुक्त राज्य",
            "उरुग्वे", "दक्षिण अफ्रीका"
        ]
        
        public static let countriesJa: [String] = [
            "アラブ首長国連邦", "アルゼンチン", "オーストラリア", "ブルガリア", "ブラジル", "バハマ", "カナダ", "スイス", "チリ", "中国",
            "コロンビア", "チェコ共和国", "デンマーク", "ドミニカ共和国", "エジプト", "ユーロ圏", "フィジー", "イギリス", "グアテマラ",
            "香港", "クロアチア", "ハンガリー", "インドネシア", "イスラエル", "インド", "アイスランド", "日本", "韓国", "カザフスタン",
            "メキシコ", "マレーシア", "ノルウェー", "ニュージーランド", "パナマ", "ペルー", "フィリピン", "パキスタン", "ポーランド",
            "パラグアイ", "ルーマニア", "ロシア", "サウジアラビア", "スウェーデン", "シンガポール", "タイ", "トルコ", "台湾", "ウクライナ",
            "アメリカ合衆国", "ウルグアイ", "南アフリカ"
        ]
        
        public static let countriesPt: [String] = [
            "Emirados Árabes Unidos", "Argentina", "Austrália", "Bulgária", "Brasil", "Bahamas", "Canadá", "Suíça", "Chile", "China",
            "Colômbia", "República Checa", "Dinamarca", "República Dominicana", "Egito", "Zona Euro", "Fiji", "Reino Unido", "Guatemala",
            "Hong Kong", "Croácia", "Hungria", "Indonésia", "Israel", "Índia", "Islândia", "Japão", "Coreia do Sul", "Cazaquistão",
            "México", "Malásia", "Noruega", "Nova Zelândia", "Panamá", "Peru", "Filipinas", "Paquistão", "Polônia", "Paraguai", "Romênia",
            "Rússia", "Arábia Saudita", "Suécia", "Singapura", "Tailândia", "Turquia", "Taiwan", "Ucrânia", "Estados Unidos", "Uruguai",
            "África do Sul"
        ]
        
        // Continue similarly for Russian, Chinese Simplified (zh-Hans), and Chinese Traditional (zh-Hant)
    }


    public static let countriesDe: [String] = [
           "Vereinigte Arabische Emirate", "Argentinien", "Australien", "Bulgarien", "Brasilien", "Bahamas", "Kanada", "Schweiz", "Chile", "China",
           "Kolumbien", "Tschechische Republik", "Dänemark", "Dominikanische Republik", "Ägypten", "Eurozone", "Fidschi", "Vereinigtes Königreich", "Guatemala",
           "Hongkong", "Kroatien", "Ungarn", "Indonesien", "Israel", "Indien", "Island", "Japan", "Südkorea", "Kasachstan", "Mexiko", "Malaysia", "Norwegen",
           "Neuseeland", "Panama", "Peru", "Philippinen", "Pakistan", "Polen", "Paraguay", "Rumänien", "Russland", "Saudi-Arabien", "Schweden", "Singapur",
           "Thailand", "Türkei", "Taiwan", "Ukraine", "Vereinigte Staaten", "Uruguay", "Südafrika"
       ]

       public static let countriesRu: [String] = [
           "Объединенные Арабские Эмираты", "Аргентина", "Австралия", "Болгария", "Бразилия", "Багамы", "Канада", "Швейцария", "Чили", "Китай",
           "Колумбия", "Чехия", "Дания", "Доминиканская Республика", "Египет", "Еврозона", "Фиджи", "Великобритания", "Гватемала", "Гонконг", "Хорватия",
           "Венгрия", "Индонезия", "Израиль", "Индия", "Исландия", "Япония", "Южная Корея", "Казахстан", "Мексика", "Малайзия", "Норвегия", "Новая Зеландия",
           "Панама", "Перу", "Филиппины", "Пакистан", "Польша", "Парагвай", "Румыния", "Россия", "Саудовская Аравия", "Швеция", "Сингапур", "Таиланд",
           "Турция", "Тайвань", "Украина", "Соединенные Штаты", "Уругвай", "Южноафриканская Республика"
       ]
       
       public static let countriesZhHans: [String] = [
           "阿联酋", "阿根廷", "澳大利亚", "保加利亚", "巴西", "巴哈马", "加拿大", "瑞士", "智利", "中国",
           "哥伦比亚", "捷克共和国", "丹麦", "多米尼加共和国", "埃及", "欧元区", "斐济", "英国", "危地马拉", "香港", "克罗地亚",
           "匈牙利", "印度尼西亚", "以色列", "印度", "冰岛", "日本", "韩国", "哈萨克斯坦", "墨西哥", "马来西亚", "挪威", "新西兰",
           "巴拿马", "秘鲁", "菲律宾", "巴基斯坦", "波兰", "巴拉圭", "罗马尼亚", "俄罗斯", "沙特阿拉伯", "瑞典", "新加坡", "泰国",
           "土耳其", "台湾", "乌克兰", "美国", "乌拉圭", "南非"
       ]

       public static let countriesZhHant: [String] = [
           "阿聯酋", "阿根廷", "澳大利亞", "保加利亞", "巴西", "巴哈馬", "加拿大", "瑞士", "智利", "中國",
           "哥倫比亞", "捷克共和國", "丹麥", "多明尼加共和國", "埃及", "歐元區", "斐濟", "英國", "危地馬拉", "香港", "克羅地亞",
           "匈牙利", "印度尼西亞", "以色列", "印度", "冰島", "日本", "韓國", "哈薩克斯坦", "墨西哥", "馬來西亞", "挪威", "新西蘭",
           "巴拿馬", "秘魯", "菲律賓", "巴基斯坦", "波蘭", "巴拉圭", "羅馬尼亞", "俄羅斯", "沙烏地阿拉伯", "瑞典", "新加坡", "泰國",
           "土耳其", "台灣", "烏克蘭", "美國", "烏拉圭", "南非"
       ]

       public static let countriesEn: [String] = [
           "United Arab Emirates", "Argentina", "Australia", "Bulgaria", "Brazil", "Bahamas", "Canada", "Switzerland", "Chile", "China",
           "Colombia", "Czech Republic", "Denmark", "Dominican Republic", "Egypt", "Eurozone", "Fiji", "United Kingdom", "Guatemala", "Hong Kong", "Croatia",
           "Hungary", "Indonesia", "Israel", "India", "Iceland", "Japan", "South Korea", "Kazakhstan", "Mexico", "Malaysia", "Norway", "New Zealand",
           "Panama", "Peru", "Philippines", "Pakistan", "Poland", "Paraguay", "Romania", "Russia", "Saudi Arabia", "Sweden", "Singapore", "Thailand",
           "Turkey", "Taiwan", "Ukraine", "United States", "Uruguay", "South Africa"
       ]

    public static let currencyCodes: [(String, String)] = [
        ("AED", "United Arab Emirates Dirham"),
        ("ARS", "Argentine Peso"),
        ("AUD", "Australian Dollar"),
        ("BGN", "Bulgarian Lev"),
        ("BRL", "Brazilian Real"),
        ("BSD", "Bahamian Dollar"),
        ("CAD", "Canadian Dollar"),
        ("CHF", "Swiss Franc"),
        ("CLP", "Chilean Peso"),
        ("CNY", "Chinese Yuan"),
        ("COP", "Colombian Peso"),
        ("CZK", "Czech Koruna"),
        ("DKK", "Danish Krone"),
        ("DOP", "Dominican Peso"),
        ("EGP", "Egyptian Pound"),
        ("EUR", "Euro"),
        ("FJD", "Fijian Dollar"),
        ("GBP", "British Pound Sterling"),
        ("GTQ", "Guatemalan Quetzal"),
        ("HKD", "Hong Kong Dollar"),
        ("HRK", "Croatian Kuna"),
        ("HUF", "Hungarian Forint"),
        ("IDR", "Indonesian Rupiah"),
        ("ILS", "Israeli New Shekel"),
        ("INR", "Indian Rupee"),
        ("ISK", "Icelandic Króna"),
        ("JPY", "Japanese Yen"),
        ("KRW", "South Korean Won"),
        ("KZT", "Kazakhstani Tenge"),
        ("MXN", "Mexican Peso"),
        ("MYR", "Malaysian Ringgit"),
        ("NOK", "Norwegian Krone"),
        ("NZD", "New Zealand Dollar"),
        ("PAB", "Panamanian Balboa"),
        ("PEN", "Peruvian Nuevo Sol"),
        ("PHP", "Philippine Peso"),
        ("PKR", "Pakistani Rupee"),
        ("PLN", "Polish Zloty"),
        ("PYG", "Paraguayan Guarani"),
        ("RON", "Romanian Leu"),
        ("RUB", "Russian Ruble"),
        ("SAR", "Saudi Riyal"),
        ("SEK", "Swedish Krona"),
        ("SGD", "Singapore Dollar"),
        ("THB", "Thai Baht"),
        ("TRY", "Turkish Lira"),
        ("TWD", "New Taiwan Dollar"),
        ("UAH", "Ukrainian Hryvnia"),
        ("USD", "United States Dollar"),
        ("UYU", "Uruguayan Peso"),
        ("ZAR", "South African Rand")
    ]

    public static let currencyCodesAr: [(String, String)] = [
        ("AED", "درهم إماراتي"),
        ("ARS", "بيزو أرجنتيني"),
        ("AUD", "دولار أسترالي"),
        ("BGN", "ليف بلغاري"),
        ("BRL", "ريال برازيلي"),
        ("BSD", "دولار بهامي"),
        ("CAD", "دولار كندي"),
        ("CHF", "فرنك سويسري"),
        ("CLP", "بيزو تشيلي"),
        ("CNY", "يوان صيني"),
        ("COP", "بيزو كولومبي"),
        ("CZK", "كورونة تشيكية"),
        ("DKK", "كرونة دنماركية"),
        ("DOP", "بيزو دومينيكاني"),
        ("EGP", "جنيه مصري"),
        ("EUR", "يورو"),
        ("FJD", "دولار فيجي"),
        ("GBP", "جنيه إسترليني"),
        ("GTQ", "كتزال غواتيمالي"),
        ("HKD", "دولار هونغ كونغ"),
        ("HRK", "كونا كرواتية"),
        ("HUF", "فورنت مجري"),
        ("IDR", "روبية إندونيسية"),
        ("ILS", "شيكل إسرائيلي جديد"),
        ("INR", "روبية هندية"),
        ("ISK", "كرونا آيسلندية"),
        ("JPY", "ين ياباني"),
        ("KRW", "وون كوري جنوبي"),
        ("KZT", "تينغي كازاخستاني"),
        ("MXN", "بيزو مكسيكي"),
        ("MYR", "رينغيت ماليزي"),
        ("NOK", "كرونة نرويجية"),
        ("NZD", "دولار نيوزيلندي"),
        ("PAB", "بالبوا بنمي"),
        ("PEN", "سول بيروفي جديد"),
        ("PHP", "بيزو فلبيني"),
        ("PKR", "روبية باكستانية"),
        ("PLN", "زلوتي بولندي"),
        ("PYG", "غواراني باراغواي"),
        ("RON", "ليو روماني"),
        ("RUB", "روبل روسي"),
        ("SAR", "ريال سعودي"),
        ("SEK", "كرونة سويدية"),
        ("SGD", "دولار سنغافوري"),
        ("THB", "بات تايلندي"),
        ("TRY", "ليرة تركية"),
        ("TWD", "دولار تايواني جديد"),
        ("UAH", "هريفنيا أوكرانية"),
        ("USD", "دولار أمريكي"),
        ("UYU", "بيزو أوروغواي"),
        ("ZAR", "راند جنوب أفريقي")
    ]

    public static let currencyCodesPt: [(String, String)] = [
        ("AED", "Dirham dos Emirados Árabes Unidos"),
        ("ARS", "Peso Argentino"),
        ("AUD", "Dólar Australiano"),
        ("BGN", "Lev Búlgaro"),
        ("BRL", "Real Brasileiro"),
        ("BSD", "Dólar Bahamense"),
        ("CAD", "Dólar Canadense"),
        ("CHF", "Franco Suíço"),
        ("CLP", "Peso Chileno"),
        ("CNY", "Yuan Chinês"),
        ("COP", "Peso Colombiano"),
        ("CZK", "Coruna Checa"),
        ("DKK", "Coroa Dinamarquesa"),
        ("DOP", "Peso Dominicano"),
        ("EGP", "Libra Egípcia"),
        ("EUR", "Euro"),
        ("FJD", "Dólar Fijiano"),
        ("GBP", "Libra Esterlina Britânica"),
        ("GTQ", "Quetzal Guatemalteco"),
        ("HKD", "Dólar de Hong Kong"),
        ("HRK", "Kuna Croata"),
        ("HUF", "Forinte Húngaro"),
        ("IDR", "Rupia Indonésia"),
        ("ILS", "Novo Shekel Israelense"),
        ("INR", "Rupia Indiana"),
        ("ISK", "Coroa Islandesa"),
        ("JPY", "Iene Japonês"),
        ("KRW", "Won Sul-Coreano"),
        ("KZT", "Tenge Cazaque"),
        ("MXN", "Peso Mexicano"),
        ("MYR", "Ringgit Malaio"),
        ("NOK", "Coroa Norueguesa"),
        ("NZD", "Dólar Neozelandês"),
        ("PAB", "Balboa Panameño"),
        ("PEN", "Novo Sol Peruano"),
        ("PHP", "Peso Filipino"),
        ("PKR", "Rupia Paquistanesa"),
        ("PLN", "Zloty Polonês"),
        ("PYG", "Guarani Paraguaio"),
        ("RON", "Leu Romeno"),
        ("RUB", "Rublo Russo"),
        ("SAR", "Riyal Saudita"),
        ("SEK", "Coroa Sueca"),
        ("SGD", "Dólar de Singapura"),
        ("THB", "Baht Tailandês"),
        ("TRY", "Lira Turca"),
        ("TWD", "Novo Dólar de Taiwan"),
        ("UAH", "Hryvnia Ucraniana"),
        ("USD", "Dólar Americano"),
        ("UYU", "Peso Uruguaio"),
        ("ZAR", "Rand Sul-Africano")
    ]

    public static let currencyCodesJa: [(String, String)] = [
        ("AED", "アラブ首長国連邦ディルハム"),
        ("ARS", "アルゼンチンペソ"),
        ("AUD", "オーストラリアドル"),
        ("BGN", "ブルガリアレフ"),
        ("BRL", "ブラジルレアル"),
        ("BSD", "バハマドル"),
        ("CAD", "カナダドル"),
        ("CHF", "スイスフラン"),
        ("CLP", "チリペソ"),
        ("CNY", "中国元"),
        ("COP", "コロンビアペソ"),
        ("CZK", "チェココルナ"),
        ("DKK", "デンマーククローネ"),
        ("DOP", "ドミニカペソ"),
        ("EGP", "エジプトポンド"),
        ("EUR", "ユーロ"),
        ("FJD", "フィジードル"),
        ("GBP", "イギリスポンド"),
        ("GTQ", "グアテマラケツァール"),
        ("HKD", "香港ドル"),
        ("HRK", "クロアチアクーナ"),
        ("HUF", "ハンガリーフォリント"),
        ("IDR", "インドネシアルピア"),
        ("ILS", "イスラエル新シェケル"),
        ("INR", "インドルピー"),
        ("ISK", "アイスランドクローナ"),
        ("JPY", "日本円"),
        ("KRW", "韓国ウォン"),
        ("KZT", "カザフスタンテンゲ"),
        ("MXN", "メキシコペソ"),
        ("MYR", "マレーシアリンギット"),
        ("NOK", "ノルウェークローネ"),
        ("NZD", "ニュージーランドドル"),
        ("PAB", "パナマバルボア"),
        ("PEN", "ペルー新ソル"),
        ("PHP", "フィリピンペソ"),
        ("PKR", "パキスタンルピー"),
        ("PLN", "ポーランドズウォティ"),
        ("PYG", "パラグアイグアラニ"),
        ("RON", "ルーマニアレウ"),
        ("RUB", "ロシアルーブル"),
        ("SAR", "サウジアラビアリヤル"),
        ("SEK", "スウェーデンクローナ"),
        ("SGD", "シンガポールドル"),
        ("THB", "タイバーツ"),
        ("TRY", "トルコリラ"),
        ("TWD", "台湾新ドル"),
        ("UAH", "ウクライナフリブニャ"),
        ("USD", "アメリカドル"),
        ("UYU", "ウルグアイペソ"),
        ("ZAR", "南アフリカランド")
    ]

    public static let currencyCodesEs: [(String, String)] = [
        ("AED", "Dirham de los Emiratos Árabes Unidos"),
        ("ARS", "Peso Argentino"),
        ("AUD", "Dólar Australiano"),
        ("BGN", "Lev Búlgaro"),
        ("BRL", "Real Brasileño"),
        ("BSD", "Dólar Bahameño"),
        ("CAD", "Dólar Canadiense"),
        ("CHF", "Franco Suizo"),
        ("CLP", "Peso Chileno"),
        ("CNY", "Yuan Chino"),
        ("COP", "Peso Colombiano"),
        ("CZK", "Corona Checa"),
        ("DKK", "Corona Danesa"),
        ("DOP", "Peso Dominicano"),
        ("EGP", "Libra Egipcia"),
        ("EUR", "Euro"),
        ("FJD", "Dólar Fijiano"),
        ("GBP", "Libra Esterlina Británica"),
        ("GTQ", "Quetzal Guatemalteco"),
        ("HKD", "Dólar de Hong Kong"),
        ("HRK", "Kuna Croata"),
        ("HUF", "Forinto Húngaro"),
        ("IDR", "Rupia Indonesia"),
        ("ILS", "Nuevo Shekel Israelí"),
        ("INR", "Rupia India"),
        ("ISK", "Corona Islandesa"),
        ("JPY", "Yen Japonés"),
        ("KRW", "Won Coreano del Sur"),
        ("KZT", "Tenge Kazajo"),
        ("MXN", "Peso Mexicano"),
        ("MYR", "Ringgit Malayo"),
        ("NOK", "Corona Noruega"),
        ("NZD", "Dólar Neozelandés"),
        ("PAB", "Balboa Panameña"),
        ("PEN", "Nuevo Sol Peruano"),
        ("PHP", "Peso Filipino"),
        ("PKR", "Rupia Pakistaní"),
        ("PLN", "Zloty Polaco"),
        ("PYG", "Guaraní Paraguayo"),
        ("RON", "Leu Rumano"),
        ("RUB", "Rublo Ruso"),
        ("SAR", "Riyal Saudí"),
        ("SEK", "Corona Sueca"),
        ("SGD", "Dólar Singapurense"),
        ("THB", "Baht Tailandés"),
        ("TRY", "Lira Turca"),
        ("TWD", "Nuevo Dólar de Taiwán"),
        ("UAH", "Grivna Ucraniana"),
        ("USD", "Dólar Estadounidense"),
        ("UYU", "Peso Uruguayo"),
        ("ZAR", "Rand Sudafricano")
    ]
    
    public static let currencyCodesDe: [(String, String)] = [
        ("AED", "Vereinigte Arabische Emirate Dirham"),
        ("ARS", "Argentinischer Peso"),
        ("AUD", "Australischer Dollar"),
        ("BGN", "Bulgarischer Lev"),
        ("BRL", "Brasilianischer Real"),
        ("BSD", "Bahama-Dollar"),
        ("CAD", "Kanadischer Dollar"),
        ("CHF", "Schweizer Franken"),
        ("CLP", "Chilenischer Peso"),
        ("CNY", "Chinesischer Yuan"),
        ("COP", "Kolumbianischer Peso"),
        ("CZK", "Tschechische Krone"),
        ("DKK", "Dänische Krone"),
        ("DOP", "Dominikanischer Peso"),
        ("EGP", "Ägyptisches Pfund"),
        ("EUR", "Euro"),
        ("FJD", "Fidschi-Dollar"),
        ("GBP", "Britisches Pfund"),
        ("GTQ", "Guatemaltekischer Quetzal"),
        ("HKD", "Hongkong-Dollar"),
        ("HRK", "Kroatische Kuna"),
        ("HUF", "Ungarischer Forint"),
        ("IDR", "Indonesische Rupiah"),
        ("ILS", "Israelischer Neuer Schekel"),
        ("INR", "Indische Rupie"),
        ("ISK", "Isländische Krone"),
        ("JPY", "Japanischer Yen"),
        ("KRW", "Südkoreanischer Won"),
        ("KZT", "Kasachische Tenge"),
        ("MXN", "Mexikanischer Peso"),
        ("MYR", "Malaysischer Ringgit"),
        ("NOK", "Norwegische Krone"),
        ("NZD", "Neuseeländischer Dollar"),
        ("PAB", "Panamaischer Balboa"),
        ("PEN", "Peruanischer Nuevo Sol"),
        ("PHP", "Philippinischer Peso"),
        ("PKR", "Pakistanische Rupie"),
        ("PLN", "Polnischer Zloty"),
        ("PYG", "Paraguayischer Guarani"),
        ("RON", "Rumänischer Leu"),
        ("RUB", "Russischer Rubel"),
        ("SAR", "Saudi-Riyal"),
        ("SEK", "Schwedische Krone"),
        ("SGD", "Singapur-Dollar"),
        ("THB", "Thailändischer Baht"),
        ("TRY", "Türkische Lira"),
        ("TWD", "Neuer Taiwan-Dollar"),
        ("UAH", "Ukrainische Hrywnja"),
        ("USD", "US-Dollar"),
        ("UYU", "Uruguayanischer Peso"),
        ("ZAR", "Südafrikanischer Rand")
    ]

    public static let currencyCodesRu: [(String, String)] = [
        ("AED", "Дирхам Объединенных Арабских Эмиратов"),
        ("ARS", "Аргентинское песо"),
        ("AUD", "Австралийский доллар"),
        ("BGN", "Болгарский лев"),
        ("BRL", "Бразильский реал"),
        ("BSD", "Багамский доллар"),
        ("CAD", "Канадский доллар"),
        ("CHF", "Швейцарский франк"),
        ("CLP", "Чилийское песо"),
        ("CNY", "Китайский юань"),
        ("COP", "Колумбийское песо"),
        ("CZK", "Чешская крона"),
        ("DKK", "Датская крона"),
        ("DOP", "Доминиканское песо"),
        ("EGP", "Египетский фунт"),
        ("EUR", "Евро"),
        ("FJD", "Фиджийский доллар"),
        ("GBP", "Британский фунт стерлингов"),
        ("GTQ", "Гватемальский кетсаль"),
        ("HKD", "Гонконгский доллар"),
        ("HRK", "Хорватская куна"),
        ("HUF", "Венгерский форинт"),
        ("IDR", "Индонезийская рупия"),
        ("ILS", "Новый израильский шекель"),
        ("INR", "Индийская рупия"),
        ("ISK", "Исландская крона"),
        ("JPY", "Японская иена"),
        ("KRW", "Южнокорейская вона"),
        ("KZT", "Казахстанский тенге"),
        ("MXN", "Мексиканское песо"),
        ("MYR", "Малайзийский ринггит"),
        ("NOK", "Норвежская крона"),
        ("NZD", "Новозеландский доллар"),
        ("PAB", "Панамский балбоа"),
        ("PEN", "Перуанский новый соль"),
        ("PHP", "Филиппинское песо"),
        ("PKR", "Пакистанская рупия"),
        ("PLN", "Польский злотый"),
        ("PYG", "Парагвайский гуарани"),
        ("RON", "Румынский лей"),
        ("RUB", "Российский рубль"),
        ("SAR", "Саудовский риял"),
        ("SEK", "Шведская крона"),
        ("SGD", "Сингапурский доллар"),
        ("THB", "Тайский бат"),
        ("TRY", "Турецкая лира"),
        ("TWD", "Новый тайваньский доллар"),
        ("UAH", "Украинская гривна"),
        ("USD", "Доллар США"),
        ("UYU", "Уругвайское песо"),
        ("ZAR", "Южноафриканский ранд")
    ]

    public static let currencyCodesZhHans: [(String, String)] = [
        ("AED", "阿联酋迪拉姆"),
        ("ARS", "阿根廷比索"),
        ("AUD", "澳大利亚元"),
        ("BGN", "保加利亚列弗"),
        ("BRL", "巴西雷亚尔"),
        ("BSD", "巴哈马美元"),
        ("CAD", "加拿大元"),
        ("CHF", "瑞士法郎"),
        ("CLP", "智利比索"),
        ("CNY", "人民币"),
        ("COP", "哥伦比亚比索"),
        ("CZK", "捷克克朗"),
        ("DKK", "丹麦克朗"),
        ("DOP", "多米尼加比索"),
        ("EGP", "埃及镑"),
        ("EUR", "欧元"),
        ("FJD", "斐济元"),
        ("GBP", "英镑"),
        ("GTQ", "危地马拉格查尔"),
        ("HKD", "港元"),
        ("HRK", "克罗地亚库纳"),
        ("HUF", "匈牙利福林"),
        ("IDR", "印度尼西亚盾"),
        ("ILS", "以色列新谢克尔"),
        ("INR", "印度卢比"),
        ("ISK", "冰岛克朗"),
        ("JPY", "日元"),
        ("KRW", "韩元"),
        ("KZT", "哈萨克斯坦腾格"),
        ("MXN", "墨西哥比索"),
        ("MYR", "马来西亚林吉特"),
        ("NOK", "挪威克朗"),
        ("NZD", "新西兰元"),
        ("PAB", "巴拿马巴尔博亚"),
        ("PEN", "秘鲁新索尔"),
        ("PHP", "菲律宾比索"),
        ("PKR", "巴基斯坦卢比"),
        ("PLN", "波兰兹罗提"),
        ("PYG", "巴拉圭瓜拉尼"),
        ("RON", "罗马尼亚列伊"),
        ("RUB", "俄罗斯卢布"),
        ("SAR", "沙特阿拉伯里亚尔"),
        ("SEK", "瑞典克朗"),
        ("SGD", "新加坡元"),
        ("THB", "泰铢"),
        ("TRY", "土耳其里拉"),
        ("TWD", "新台币"),
        ("UAH", "乌克兰格里夫纳"),
        ("USD", "美元"),
        ("UYU", "乌拉圭比索"),
        ("ZAR", "南非兰特")
    ]

    public static let currencyCodesZhHant: [(String, String)] = [
        ("AED", "阿聯酋迪拉姆"),
        ("ARS", "阿根廷比索"),
        ("AUD", "澳大利亞元"),
        ("BGN", "保加利亞列弗"),
        ("BRL", "巴西雷亞爾"),
        ("BSD", "巴哈馬美元"),
        ("CAD", "加拿大元"),
        ("CHF", "瑞士法郎"),
        ("CLP", "智利比索"),
        ("CNY", "人民幣"),
        ("COP", "哥倫比亞比索"),
        ("CZK", "捷克克朗"),
        ("DKK", "丹麥克朗"),
        ("DOP", "多米尼加比索"),
        ("EGP", "埃及鎊"),
        ("EUR", "歐元"),
        ("FJD", "斐濟元"),
        ("GBP", "英鎊"),
        ("GTQ", "危地馬拉格查爾"),
        ("HKD", "港元"),
        ("HRK", "克羅地亞庫納"),
        ("HUF", "匈牙利福林"),
        ("IDR", "印尼盾"),
        ("ILS", "以色列新謝克爾"),
        ("INR", "印度盧比"),
        ("ISK", "冰島克朗"),
        ("JPY", "日元"),
        ("KRW", "韓元"),
        ("KZT", "哈薩克斯坦騰格"),
        ("MXN", "墨西哥比索"),
        ("MYR", "馬來西亞林吉特"),
        ("NOK", "挪威克朗"),
        ("NZD", "新西蘭元"),
        ("PAB", "巴拿馬巴爾博亞"),
        ("PEN", "秘魯新索爾"),
        ("PHP", "菲律賓比索"),
        ("PKR", "巴基斯坦盧比"),
        ("PLN", "波蘭茲羅提"),
        ("PYG", "巴拉圭瓜拉尼"),
        ("RON", "羅馬尼亞列伊"),
        ("RUB", "俄羅斯盧布"),
        ("SAR", "沙特阿拉伯里亞爾"),
        ("SEK", "瑞典克朗"),
        ("SGD", "新加坡元"),
        ("THB", "泰銖"),
        ("TRY", "土耳其里拉"),
        ("TWD", "新台幣"),
        ("UAH", "烏克蘭格里夫納"),
        ("USD", "美元"),
        ("UYU", "烏拉圭比索"),
        ("ZAR", "南非蘭特")
    ]
    
    public static let currencyCodesEn: [(String, String)] = [
        ("AED", "United Arab Emirates Dirham"),
        ("ARS", "Argentine Peso"),
        ("AUD", "Australian Dollar"),
        ("BGN", "Bulgarian Lev"),
        ("BRL", "Brazilian Real"),
        ("BSD", "Bahamian Dollar"),
        ("CAD", "Canadian Dollar"),
        ("CHF", "Swiss Franc"),
        ("CLP", "Chilean Peso"),
        ("CNY", "Chinese Yuan"),
        ("COP", "Colombian Peso"),
        ("CZK", "Czech Koruna"),
        ("DKK", "Danish Krone"),
        ("DOP", "Dominican Peso"),
        ("EGP", "Egyptian Pound"),
        ("EUR", "Euro"),
        ("FJD", "Fijian Dollar"),
        ("GBP", "British Pound Sterling"),
        ("GTQ", "Guatemalan Quetzal"),
        ("HKD", "Hong Kong Dollar"),
        ("HRK", "Croatian Kuna"),
        ("HUF", "Hungarian Forint"),
        ("IDR", "Indonesian Rupiah"),
        ("ILS", "Israeli New Shekel"),
        ("INR", "Indian Rupee"),
        ("ISK", "Icelandic Króna"),
        ("JPY", "Japanese Yen"),
        ("KRW", "South Korean Won"),
        ("KZT", "Kazakhstani Tenge"),
        ("MXN", "Mexican Peso"),
        ("MYR", "Malaysian Ringgit"),
        ("NOK", "Norwegian Krone"),
        ("NZD", "New Zealand Dollar"),
        ("PAB", "Panamanian Balboa"),
        ("PEN", "Peruvian Nuevo Sol"),
        ("PHP", "Philippine Peso"),
        ("PKR", "Pakistani Rupee"),
        ("PLN", "Polish Zloty"),
        ("PYG", "Paraguayan Guarani"),
        ("RON", "Romanian Leu"),
        ("RUB", "Russian Ruble"),
        ("SAR", "Saudi Riyal"),
        ("SEK", "Swedish Krona"),
        ("SGD", "Singapore Dollar"),
        ("THB", "Thai Baht"),
        ("TRY", "Turkish Lira"),
        ("TWD", "New Taiwan Dollar"),
        ("UAH", "Ukrainian Hryvnia"),
        ("USD", "United States Dollar"),
        ("UYU", "Uruguayan Peso"),
        ("ZAR", "South African Rand")
    ]


    public static let currencyCodesHi: [(String, String)] = [
        ("AED", "संयुक्त अरब अमीरात दिरहम"),
        ("ARS", "अर्जेंटीना पेसो"),
        ("AUD", "ऑस्ट्रेलियाई डॉलर"),
        ("BGN", "बल्गेरियाई लेव"),
        ("BRL", "ब्राज़ीलियाई रीयल"),
        ("BSD", "बहामियन डॉलर"),
        ("CAD", "कनाडाई डॉलर"),
        ("CHF", "स्विस फ्रैंक"),
        ("CLP", "चिली पेसो"),
        ("CNY", "चीनी युआन"),
        ("COP", "कोलंबियाई पेसो"),
        ("CZK", "चेक क्राउन"),
        ("DKK", "डेनिश क्रोन"),
        ("DOP", "डोमिनिकन पेसो"),
        ("EGP", "मिस्र पाउंड"),
        ("EUR", "यूरो"),
        ("FJD", "फिजी डॉलर"),
        ("GBP", "ब्रिटिश पाउंड स्टर्लिंग"),
        ("GTQ", "ग्वाटेमाला क्वेट्जल"),
        ("HKD", "हांगकांग डॉलर"),
        ("HRK", "क्रोएशियाई कुना"),
        ("HUF", "हंगेरियन फोरिंट"),
        ("IDR", "इंडोनेशियाई रुपिया"),
        ("ILS", "इज़राइली नया शेकल"),
        ("INR", "भारतीय रुपया"),
        ("ISK", "आइसलैंडिक क्रोना"),
        ("JPY", "जापानी येन"),
        ("KRW", "दक्षिण कोरियाई वॉन"),
        ("KZT", "कज़ाख़स्तानी तेंगे"),
        ("MXN", "मैक्सिकन पेसो"),
        ("MYR", "मलेशियाई रिंगगिट"),
        ("NOK", "नॉर्वेजियन क्रोन"),
        ("NZD", "न्यूजीलैंड डॉलर"),
        ("PAB", "पानामियन बालबोआ"),
        ("PEN", "पेरूवियन नूवो सोल"),
        ("PHP", "फिलीपीन पेसो"),
        ("PKR", "पाकिस्तानी रुपया"),
        ("PLN", "पोलिश ज़्लोटी"),
        ("PYG", "पैराग्वे गुआरानी"),
        ("RON", "रोमानी लियु"),
        ("RUB", "रूसी रूबल"),
        ("SAR", "सऊदी रियाल"),
        ("SEK", "स्वीडिश क्रोन"),
        ("SGD", "सिंगापुर डॉलर"),
        ("THB", "थाई बात"),
        ("TRY", "तुर्की लीरा"),
        ("TWD", "नया ताइवानी डॉलर"),
        ("UAH", "यूक्रेनी ह्रिव्निया"),
        ("USD", "अमेरिकी डॉलर"),
        ("UYU", "उरुग्वे पेसो"),
        ("ZAR", "दक्षिण अफ्रीकी रैंड")
    ]

    public static let currencyCodesFr: [(String, String)] = [
        ("AED", "Dirham des Émirats Arabes Unis"),
        ("ARS", "Peso Argentin"),
        ("AUD", "Dollar Australien"),
        ("BGN", "Lev Bulgare"),
        ("BRL", "Real Brésilien"),
        ("BSD", "Dollar Bahaméen"),
        ("CAD", "Dollar Canadien"),
        ("CHF", "Franc Suisse"),
        ("CLP", "Peso Chilien"),
        ("CNY", "Yuan Chinois"),
        ("COP", "Peso Colombien"),
        ("CZK", "Couronne Tchèque"),
        ("DKK", "Couronne Danoise"),
        ("DOP", "Peso Dominicain"),
        ("EGP", "Livre Égyptienne"),
        ("EUR", "Euro"),
        ("FJD", "Dollar Fidjien"),
        ("GBP", "Livre Sterling Britannique"),
        ("GTQ", "Quetzal Guatémaltèque"),
        ("HKD", "Dollar Hongkongais"),
        ("HRK", "Kuna Croate"),
        ("HUF", "Forint Hongrois"),
        ("IDR", "Roupie Indonésienne"),
        ("ILS", "Shekel Nouveau Israélien"),
        ("INR", "Roupie Indienne"),
        ("ISK", "Couronne Islandaise"),
        ("JPY", "Yen Japonais"),
        ("KRW", "Won Sud-Coréen"),
        ("KZT", "Tenge Kazakh"),
        ("MXN", "Peso Mexicain"),
        ("MYR", "Ringgit Malaisien"),
        ("NOK", "Couronne Norvégienne"),
        ("NZD", "Dollar Néo-Zélandais"),
        ("PAB", "Balboa Panaméen"),
        ("PEN", "Nuevo Sol Péruvien"),
        ("PHP", "Peso Philippin"),
        ("PKR", "Roupie Pakistanaise"),
        ("PLN", "Zloty Polonais"),
        ("PYG", "Guarani Paraguyen"),
        ("RON", "Leu Roumain"),
        ("RUB", "Rouble Russe"),
        ("SAR", "Riyal Saoudien"),
        ("SEK", "Couronne Suédoise"),
        ("SGD", "Dollar Singapourien"),
        ("THB", "Baht Thaïlandais"),
        ("TRY", "Livre Turque"),
        ("TWD", "Nouveau Dollar de Taïwan"),
        ("UAH", "Hryvnia Ukrainienne"),
        ("USD", "Dollar Américain"),
        ("UYU", "Peso Uruguayen"),
        ("ZAR", "Rand Sud-Africain")
    ]

}
